#!/usr/bin/env python

import argparse
import subprocess
import sys
from urllib.parse import urlparse


def dns(domain: str) -> None:
    if not domain.startswith('http'):
        domain = 'https://' + domain

    hostname = urlparse(domain).hostname

    if hostname is None:
        raise ValueError('error: invalid domain')

    types = ['A', 'AAAA', 'CNAME', 'NS', 'PTR', 'SOA', 'MX', 'SRV', 'TXT', 'CAA']
    for type in types:
        record = subprocess.run(['dig', '+nocmd', '+noall', '+answer', '+nomultiline', '+tries=2', '+time=2', hostname, type], check=True, capture_output=True, text=True).stdout.strip('\n')
        if len(record):
            print(record)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='dns records lookup')
    parser.add_argument('domain', type=str, help='domain name')
    args = parser.parse_args()
    try:
        dns(args.domain)
    except ValueError as e:
        print('error:', e, file=sys.stderr)
        sys.exit(1)

